spring.application.name=helpdesk-api
# ===================================================================
# CONFIGURA��O DO BANCO DE DADOS (PostgreSQL)
# ===================================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/helpti_db
spring.datasource.username=postgres
spring.datasource.password=postgres
server.port=8082
# ===================================================================
# CONFIGURA��O DO JPA / HIBERNATE (O "Tradutor" do Banco)
# ===================================================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Chave secreta para assinar os tokens JWT
api.security.token.secret=minha-chave-secreta-muito-longa-e-segura-do-helpti

# ===================================================================
# CONFIGURAÇÃO DO STORAGE DE ARQUIVOS
# ===================================================================
# Mude este caminho para a pasta que você criou no seu Ubuntu!
storage.location=/home/ykaro/Desktop/helpti-uploads

spring.jpa.hibernate.ddl-auto=update

# Configuração de E-mail (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=s.ykaro314@gmail.com
spring.mail.password=klxfprlygsvyeekv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true